version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - app_network

  app1:
    build: ./app
    container_name: spring_app_1
    environment:
      HOSTNAME: spring_app_1
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  app2:
    build: ./app
    container_name: spring_app_2
    environment:
      HOSTNAME: spring_app_2
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8082:8080"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
